# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md
  - contact.md

footer: '<a href="https://twitter.com/">twitter</a>'

style: dark
remote_theme: b2a3e8/jekyll-theme-console
